#!/usr/bin/env Rscript

library(tidyverse)

"Usage:
   list_reinfected_patients.R [--snp_dists <snp_dists> --metadata <metadata> --threshold <threshold>]

Options:
   --snp_dists A matrix generated by snp-dists
   --metadata Genome metadata
   --threshold SNP distance threshold to define reinfection
   
" -> doc 

opts <- docopt::docopt(doc)

list_reinfected_patients <- function(SNP_DISTS, METADATA, threshold = 20) {
  
  cols <- c("patient", "genome_1", "genome_2", "snp_dist")
  
  snp_dists <- read_delim(SNP_DISTS)
  
  metadata <- read_delim(METADATA)
  
  reinfected_patients <- snp_dists %>%
    dplyr::rename(genome_1 = 1) %>%
    pivot_longer(!genome_1, names_to = "genome_2", values_to = "snp_dist") %>%
    filter(genome_1 != genome_2) %>%
    inner_join(metadata, by = c("genome_1" = "isolate")) %>%
    inner_join(metadata[,c(1, 2)], by = c("genome_2" = "isolate")) %>%
    filter(patient.x == patient.y & time_from_diagnosis == 0) %>%
    select(4, 1:3) %>%
    setNames(cols) %>%
    filter(snp_dist > threshold) %>%
    pull(patient) %>%
    unique() %>%
    sort()
  
  writeLines(reinfected_patients, "data/reinfected_patients.txt")
  
  patients <- metadata %>%
    filter(!patient %in% reinfected_patients) %>%
    pull(patient) %>%
    unique() %>%
    sort()
  
  writeLines(patients, "data/patients.txt")
  
}

if (sys.nframe() == 0) {
  list_reinfected_patients(opts$snp_dists, opts$metadata, as.numeric(opts$threshold))
}
